name: Test

"on":
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '.github/**'
      - '.vscode/**'
      
permissions:
  pull-requests: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
        
      - name: Run Test Cases
        id: test
        run: |
          echo 'BUILD_ERRORS<<EOF' >> $GITHUB_OUTPUT
          echo "BUILD_ERRORS=$(go test ./... -v 2>&1)\n" >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
          go test ./... -v
          
      - name: Output Unit Test errors
        if: failure()
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: Testcase Error
          message: |
            **Testcases Failed** :x:
            ```
            ${{ join(steps.build.outputs.*, '\n') }}
            ```
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
